### ISSUE TITLE
Sort out parent names

### ISSUE THREAD

**Issue by QBFreak** [QBFreak/SolarWindsMARE#1]
Some parents have odd names left over from previous designs of space to include larger units than sectors. All references to Sector x Parent should probably be dropped in favor of Space x Parent.

**Existing Parent names:**
 * [x] Generic Function Parent(#4bh)
 * [x] Cron Parent(#5Vbh)
 * [x] TinyFugue Textencode Decoder Parent(#6bh)
 * [x] Communication Coordination Server Parent(#12Vbh)
 * [x] Communication Coordination Client Parent(#13Vbh)
 * [X] System Function Parent(#29h)
 * [ ] Sector Exit Parent(#45h)
 * [ ] Station Zone Parent(#46h)
 * [X] Airlock Parent(#47h)
 * [ ] Docking Collar Parent(#48h)
 * [ ] Ship Parent(#50h)
 * [ ] Ship Zone Parent(#59h)
 * [ ] Motd Parent(#66)
 * [ ] Who Parent(#67)
 * [ ] Player Character Parent(#68h)
 * [x] PlusCom Parent(#71)
 * [x] Apartment Parent(#92h)
 * [x] Apartment Bot Parent(#93h)
 * [x] Apartment Zone Parent(#96h)
 * [ ] Station Parent(#99h)
 * [ ] Station Control Console Parent(#102h)
 * [ ] Apartment Exit Parent(#104)
 * [ ] Sector Zone Parent(#110h)
 * [ ] Sector Parent(#114h)
 * [x] ID List Parent(#115h)
 * [x] ID List Manager Parent(#116h)
 * [x] Age Limited List Parent(#118h)
 * [ ] ComCname Parent(#119h)
 * [ ] Text Formatting Parent(#120)
 * [ ] Player Command Parent(#121h)
 * [ ] Space Object Parent(#124h)
 * [ ] Planet Parent(#125h)
 * [ ] Star Parent(#126)
 * [ ] Moon Parent(#143)
 * [ ] Asteroid Field Parent(#146)
 * [ ] Command Help Parent(#148h)
 * [ ] Enterable Space Object Parent(#149h)
 * [x] Todo List Parent V2(#156Vbh)
 * [x] Com Shortcut Parent(#160)
 * [ ] Planet Exit Parent(#161h)
 * [ ] Planet Zone Parent(#165h)
 * [x] 2D Coordinate System Parent(#170h)
 * [ ] Planet Function Parent(#175h)
 * [ ] Planet Room Parent(#180h)
 * [ ] Comtitle Manager Parent(#188h)
 * [ ] 2D Exit Parent(#201h)
 * [ ] ID List Manager Parent(#216)
